name: SensorPlugin
version: '${version}'
main: org.cjohnson.sensorplugin.SensorPlugin
api-version: 1.19
commands:
  sensor:
    description: Base plugin command.
  slime:
    description: Finds if slime chunk or not